### ISSUE TITLE
is it possible to avoid loading  Ionicons?

### ISSUE THREAD

**Issue by intergleam** [jkuri/ng2-datepicker#132]
I don't want to load another megabyte in my app, I am using Font Awesome already.
Thanks

**Comment by elebetsamer** [comment]
Just for reference, I used these styles to avoid loading Ionicons, as I was also already using FontAwesome.

_Note_: I'm using SCSS and so I'm using the `fa-icon` mixin from the FontAwesome scss, and some of the FontAwesome variables to set the **content**.

```scss
.datepicker-container {
    .ion-android-close,
    .ion-arrow-right-c,
    .ion-ios-arrow-back,
    .ion-ios-arrow-forward,
    .ion-ios-calendar-outline {
        @include fa-icon();
    }

    .ion-android-close:before {
        content: $fa-var-times;
    }

    .ion-arrow-right-c:before {
        content: $fa-var-arrow-right;
    }

    .ion-ios-arrow-back:before {
        content: $fa-var-angle-left;
    }

    .ion-ios-arrow-forward:before {
        content: $fa-var-angle-right;
    }

    .ion-ios-calendar-outline:before {
        content: $fa-var-calendar-o;
    }
}
```
